@extends('admin.layouts.app')

@section('content')
@php
    $user = $analytics['user'];
    $r = $analytics['revenue'];
    $ret = $analytics['retention'];
    $loy = $analytics['loyalty'];
    $beh = $analytics['behavioral'];
    $status = $analytics['status'];
    $cf = $analytics['chart_order_freq'] ?? ['labels' => [], 'data' => []];
    $or = $analytics['chart_orders_revenue'] ?? ['labels' => [], 'orders' => [], 'revenue' => []];
    $cc = $analytics['chart_category'] ?? ['labels' => [], 'data' => []];
    $cl = $analytics['chart_loyalty'] ?? ['labels' => [], 'earned' => [], 'redeemed' => []];
@endphp
<div class="max-w-[1800px] mx-auto">
    <x-breadcrumbs :items="['Customers' => route('admin.customers.index'), $user->name => null]" />

    {{-- Header --}}
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
        <div>
            <h1 class="text-2xl font-bold" style="color: var(--admin-text);">{{ $user->name }}</h1>
            <p class="mt-1" style="color: var(--admin-text-muted);">{{ $user->email }}</p>
            <div class="mt-3 flex flex-wrap items-center gap-3">
                <span class="px-3 py-1 rounded-full text-sm font-medium
                    {{ $status === 'active' ? 'bg-emerald-500/20 text-emerald-400' : '' }}
                    {{ $status === 'dormant' ? 'bg-amber-500/20 text-amber-400' : '' }}
                    {{ $status === 'inactive' ? 'bg-gray-500/20 text-gray-400' : '' }}">
                    {{ ucfirst($status) }}
                </span>
                <a href="{{ route('admin.customers.index') }}" class="text-sm" style="color: #60a5fa;">← Back to customers</a>
                <a href="{{ route('admin.customers.export.summary', $user) }}"
                    class="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition"
                    style="background: rgba(37,99,235,0.2); color: #60a5fa; border: 1px solid rgba(37,99,235,0.4);">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                    Export Summary
                </a>
            </div>
        </div>
    </div>

    {{-- Metric cards row 1: Revenue --}}
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
        <x-admin.metric-card title="Lifetime Spend" :value="'₹' . number_format($r['lifetime_spend'], 2)"
            subtitle="Total revenue generated by this customer."
            tooltip="Sum of all completed orders placed by this customer." />
        <x-admin.metric-card title="Total Orders" :value="$r['total_orders']"
            subtitle="Total number of orders placed." />
        <x-admin.metric-card title="Avg Order Value" :value="'₹' . number_format($r['avg_order_value'], 2)"
            subtitle="Average amount spent per order."
            tooltip="Calculated as total spend divided by total number of orders." />
        <x-admin.metric-card title="Highest Order" :value="'₹' . number_format($r['highest_order'], 2)"
            subtitle="Largest single purchase made." />
        <x-admin.metric-card title="Orders (30d)" :value="$r['orders_last_30']"
            subtitle="Orders in the last 30 days." />
        <x-admin.metric-card title="Orders (90d)" :value="$r['orders_last_90']"
            subtitle="Orders in the last 90 days." />
    </div>

    {{-- Metric cards row 2: Retention --}}
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 mb-8">
        <x-admin.metric-card title="Account Created" :value="$ret['account_created']?->format('M d, Y') ?? '—'" compact
            subtitle="Date when the account was registered." />
        <x-admin.metric-card title="Last Login" :value="$ret['last_login']?->format('M d, Y H:i') ?? '—'" compact
            subtitle="Most recent login to the platform." />
        <x-admin.metric-card title="Logins (30d)" :value="$ret['login_count_30']" compact
            subtitle="Recent platform engagement."
            tooltip="Number of active sessions in the last 30 days." />
        <x-admin.metric-card title="Days Since Last Order" :value="$ret['days_since_last_order'] !== null ? $ret['days_since_last_order'] . ' days' : '—'" compact
            subtitle="How long since their most recent purchase."
            tooltip="Higher values may indicate churn risk." />
        <x-admin.metric-card title="Avg Days Between Orders" :value="$ret['avg_days_between_orders'] ?: '—'" compact
            subtitle="Typical time gap between purchases." />
    </div>

    {{-- Metric cards row 3: Loyalty + Behavioral --}}
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
        <x-admin.metric-card title="Current Points" :value="$loy['current_points']"
            subtitle="Points available for future discounts." />
        <x-admin.metric-card title="Lifetime Earned" :value="$loy['lifetime_earned']" compact
            subtitle="Total points earned from purchases." />
        <x-admin.metric-card title="Lifetime Redeemed" :value="$loy['lifetime_redeemed']" compact
            subtitle="Total points used for discounts." />
        <x-admin.metric-card title="Redemption Rate" :value="$loy['redemption_rate_pct'] . '%'" compact
            subtitle="Percentage of earned points that were used."
            tooltip="(Total redeemed ÷ total earned) × 100" />
        <x-admin.metric-card title="Top Category" :value="$beh['most_purchased_category'] ?? '—'" compact truncate
            subtitle="Category this customer buys from the most." />
        <x-admin.metric-card title="Revenue Share" :value="$beh['contribution_pct'] . '%'" compact
            subtitle="Contribution to total store revenue."
            tooltip="Customer lifetime spend divided by total store revenue." />
    </div>

    {{-- Charts grid --}}
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        <div class="rounded-xl p-6" style="background: rgba(255,255,255,0.04); border: 1px solid var(--admin-border);">
            <h3 class="text-sm font-semibold uppercase mb-1" style="color: var(--admin-text-muted);">Order Frequency (Monthly)</h3>
            <p class="text-xs mb-4" style="color: var(--admin-text-muted); opacity: 0.85;">Shows how frequently this customer places orders over time.</p>
            <div class="h-64">
                <canvas id="chartOrderFreq"></canvas>
            </div>
        </div>
        <div class="rounded-xl p-6" style="background: rgba(255,255,255,0.04); border: 1px solid var(--admin-border);">
            <h3 class="text-sm font-semibold uppercase mb-1" style="color: var(--admin-text-muted);">Orders vs Revenue (Monthly)</h3>
            <p class="text-xs mb-4" style="color: var(--admin-text-muted); opacity: 0.85;">Compares spending and purchase volume month by month.</p>
            <div class="h-64">
                <canvas id="chartOrdersRevenue"></canvas>
            </div>
        </div>
        <div class="rounded-xl p-6" style="background: rgba(255,255,255,0.04); border: 1px solid var(--admin-border);">
            <h3 class="text-sm font-semibold uppercase mb-1" style="color: var(--admin-text-muted);">Category Distribution</h3>
            <p class="text-xs mb-4" style="color: var(--admin-text-muted); opacity: 0.85;">Breakdown of purchases by product category.</p>
            <div class="h-64 flex items-center justify-center">
                <canvas id="chartCategory"></canvas>
            </div>
        </div>
        <div class="rounded-xl p-6" style="background: rgba(255,255,255,0.04); border: 1px solid var(--admin-border);">
            <h3 class="text-sm font-semibold uppercase mb-1" style="color: var(--admin-text-muted);">Loyalty Points Trend</h3>
            <p class="text-xs mb-4" style="color: var(--admin-text-muted); opacity: 0.85;">Tracks points earned vs redeemed over time.</p>
            <div class="h-64">
                <canvas id="chartLoyalty"></canvas>
            </div>
        </div>
    </div>

    {{-- Purchase History --}}
    <div class="rounded-xl p-6 mb-8" style="background: rgba(255,255,255,0.04); border: 1px solid var(--admin-border);">
        <h3 class="text-sm font-semibold uppercase mb-4" style="color: var(--admin-text-muted);">Purchase History</h3>

        @if ($purchaseHistory->isEmpty())
            <div class="py-12 text-center rounded-lg" style="background: rgba(255,255,255,0.02); border: 1px dashed var(--admin-border);">
                <p class="text-base" style="color: var(--admin-text-muted);">No purchases yet.</p>
                <p class="text-sm mt-1" style="color: var(--admin-text-muted); opacity: 0.85;">Orders will appear here when this customer places an order.</p>
            </div>
        @else
            {{-- Desktop: table --}}
            <div class="hidden md:block overflow-x-auto -mx-2">
                <table class="min-w-full text-left">
                    <thead>
                        <tr class="border-b" style="border-color: var(--admin-border);">
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Order ID</th>
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Date & time</th>
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Items</th>
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Total</th>
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Payment</th>
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Status</th>
                            <th class="p-3 text-xs font-medium uppercase" style="color: var(--admin-text-muted);">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($purchaseHistory as $order)
                            <tr class="border-b admin-row-hover" style="border-color: var(--admin-border);">
                                <td class="p-3 font-medium" style="color: var(--admin-text);">#{{ $order->id }}</td>
                                <td class="p-3 text-sm" style="color: var(--admin-text);">{{ $order->created_at->format('M d, Y H:i') }}</td>
                                <td class="p-3 text-sm" style="color: var(--admin-text);">
                                    <ul class="list-disc list-inside space-y-0.5">
                                        @foreach ($order->items as $item)
                                            <li>{{ optional($item->product)->name ?? 'Product #' . $item->product_id }} × {{ $item->quantity }}</li>
                                        @endforeach
                                    </ul>
                                </td>
                                <td class="p-3 font-medium" style="color: var(--admin-text);">₹{{ number_format($order->total, 2) }}</td>
                                <td class="p-3">
                                    @php
                                        $paymentLabel = in_array($order->status, ['paid','shipped','completed']) ? 'Paid' : ($order->status === 'cancelled' ? 'Cancelled' : 'Pending');
                                        $paymentClass = $paymentLabel === 'Paid' ? 'bg-emerald-500/20 text-emerald-400' : ($paymentLabel === 'Cancelled' ? 'bg-red-500/20 text-red-400' : 'bg-amber-500/20 text-amber-400');
                                    @endphp
                                    <span class="px-2 py-0.5 text-xs rounded-full {{ $paymentClass }}">{{ $paymentLabel }}</span>
                                </td>
                                <td class="p-3">
                                    <span class="px-2 py-0.5 text-xs rounded-full
                                        {{ $order->status === 'completed' ? 'bg-emerald-500/20 text-emerald-400' : '' }}
                                        {{ $order->status === 'shipped' ? 'bg-blue-500/20 text-blue-400' : '' }}
                                        {{ $order->status === 'paid' ? 'bg-blue-500/20 text-blue-400' : '' }}
                                        {{ $order->status === 'pending' ? 'bg-amber-500/20 text-amber-400' : '' }}
                                        {{ $order->status === 'cancelled' ? 'bg-red-500/20 text-red-400' : '' }}
                                        {{ !in_array($order->status, ['completed','shipped','paid','pending','cancelled']) ? 'bg-gray-500/20 text-gray-400' : '' }}">
                                        {{ ucfirst($order->status) }}
                                    </span>
                                </td>
                                <td class="p-3">
                                    <a href="{{ route('admin.orders.show', $order) }}" class="text-sm font-medium transition hover:opacity-90" style="color: #60a5fa;">View</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            {{-- Mobile: cards --}}
            <div class="md:hidden space-y-4">
                @foreach ($purchaseHistory as $order)
                    <div class="p-4 rounded-lg admin-row-hover" style="background: rgba(255,255,255,0.02); border: 1px solid var(--admin-border);">
                        <div class="flex flex-wrap items-center justify-between gap-2 mb-3">
                            <span class="font-semibold" style="color: var(--admin-text);">#{{ $order->id }}</span>
                            <span class="text-sm" style="color: var(--admin-text-muted);">{{ $order->created_at->format('M d, Y H:i') }}</span>
                        </div>
                        <ul class="text-sm space-y-1 mb-3" style="color: var(--admin-text-muted);">
                            @foreach ($order->items as $item)
                                <li>{{ optional($item->product)->name ?? 'Product #' . $item->product_id }} × {{ $item->quantity }}</li>
                            @endforeach
                        </ul>
                        <div class="flex flex-wrap items-center justify-between gap-2 pt-2 border-t" style="border-color: var(--admin-border);">
                            <span class="font-medium" style="color: var(--admin-text);">₹{{ number_format($order->total, 2) }}</span>
                            <div class="flex flex-wrap gap-2">
                                @php
                                    $paymentLabel = in_array($order->status, ['paid','shipped','completed']) ? 'Paid' : ($order->status === 'cancelled' ? 'Cancelled' : 'Pending');
                                    $paymentClass = $paymentLabel === 'Paid' ? 'bg-emerald-500/20 text-emerald-400' : ($paymentLabel === 'Cancelled' ? 'bg-red-500/20 text-red-400' : 'bg-amber-500/20 text-amber-400');
                                @endphp
                                <span class="px-2 py-0.5 text-xs rounded-full {{ $paymentClass }}">{{ $paymentLabel }}</span>
                                <span class="px-2 py-0.5 text-xs rounded-full
                                    {{ $order->status === 'completed' ? 'bg-emerald-500/20 text-emerald-400' : '' }}
                                    {{ $order->status === 'shipped' ? 'bg-blue-500/20 text-blue-400' : '' }}
                                    {{ $order->status === 'paid' ? 'bg-blue-500/20 text-blue-400' : '' }}
                                    {{ $order->status === 'pending' ? 'bg-amber-500/20 text-amber-400' : '' }}
                                    {{ $order->status === 'cancelled' ? 'bg-red-500/20 text-red-400' : '' }}
                                    {{ !in_array($order->status, ['completed','shipped','paid','pending','cancelled']) ? 'bg-gray-500/20 text-gray-400' : '' }}">{{ ucfirst($order->status) }}</span>
                            </div>
                        </div>
                        <a href="{{ route('admin.orders.show', $order) }}" class="inline-block mt-3 text-sm font-medium transition hover:opacity-90" style="color: #60a5fa;">View order →</a>
                    </div>
                @endforeach
            </div>

            @if ($purchaseHistory->hasPages())
                <div class="mt-4 pt-4 border-t" style="border-color: var(--admin-border);">
                    {{ $purchaseHistory->links() }}
                </div>
            @endif
        @endif
    </div>

    {{-- Referral info --}}
    @if ($beh['referral_count'] > 0 || $user->referred_by)
        <div class="rounded-xl p-6 mb-8" style="background: rgba(255,255,255,0.04); border: 1px solid var(--admin-border);">
            <h3 class="text-sm font-semibold uppercase mb-3" style="color: var(--admin-text-muted);">Referrals</h3>
            <div class="flex flex-wrap gap-6">
                @if ($user->referred_by)
                    <div><span style="color: var(--admin-text-muted);">Referred by:</span> <span style="color: var(--admin-text);">{{ $user->referred_by }}</span></div>
                @endif
                @if ($beh['referral_count'] > 0)
                    <div><span style="color: var(--admin-text-muted);">Referred:</span> <span style="color: var(--admin-text);">{{ $beh['referral_count'] }} customers</span></div>
                @endif
            </div>
        </div>
    @endif
</div>

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<script>
(function() {
    Chart.defaults.color = '#71717A';
    Chart.defaults.borderColor = 'rgba(255,255,255,0.08)';
    const colors = ['#2563EB','#10B981','#F59E0B','#EF4444','#8B5CF6','#06B6D4','#EC4899','#84CC16'];

    const cf = @json($cf);
    if (cf.labels && cf.labels.length) {
        new Chart(document.getElementById('chartOrderFreq'), {
            type: 'line',
            data: {
                labels: cf.labels,
                datasets: [{
                    label: 'Orders',
                    data: cf.data,
                    borderColor: '#2563EB',
                    backgroundColor: 'rgba(37,99,235,0.1)',
                    fill: true,
                    tension: 0.3
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { display: false } },
                scales: {
                    y: { beginAtZero: true, ticks: { stepSize: 1 } }
                }
            }
        });
    } else {
        document.getElementById('chartOrderFreq').parentElement.innerHTML = '<p class="text-center" style="color: var(--admin-text-muted);">No order data</p>';
    }

    const or = @json($or);
    if (or.labels && or.labels.length) {
        new Chart(document.getElementById('chartOrdersRevenue'), {
            type: 'bar',
            data: {
                labels: or.labels,
                datasets: [
                    { label: 'Orders', data: or.orders, backgroundColor: 'rgba(37,99,235,0.6)' },
                    { label: 'Revenue (₹)', data: or.revenue, backgroundColor: 'rgba(16,185,129,0.6)' }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { position: 'top' } },
                scales: {
                    y: { beginAtZero: true }
                }
            }
        });
    } else {
        document.getElementById('chartOrdersRevenue').parentElement.innerHTML = '<p class="text-center" style="color: var(--admin-text-muted);">No order data</p>';
    }

    const cc = @json($cc);
    if (cc.labels && cc.labels.length) {
        new Chart(document.getElementById('chartCategory'), {
            type: 'doughnut',
            data: {
                labels: cc.labels,
                datasets: [{
                    data: cc.data,
                    backgroundColor: colors.slice(0, cc.labels.length)
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { position: 'right' } }
            }
        });
    } else {
        document.getElementById('chartCategory').parentElement.innerHTML = '<p class="text-center" style="color: var(--admin-text-muted);">No category data</p>';
    }

    const cl = @json($cl);
    if (cl.labels && cl.labels.length) {
        new Chart(document.getElementById('chartLoyalty'), {
            type: 'line',
            data: {
                labels: cl.labels,
                datasets: [
                    { label: 'Earned (cumulative)', data: cl.earned, borderColor: '#10B981', fill: false, tension: 0.3 },
                    { label: 'Redeemed (cumulative)', data: cl.redeemed, borderColor: '#F59E0B', fill: false, tension: 0.3 }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { position: 'top' } },
                scales: {
                    y: { beginAtZero: true }
                }
            }
        });
    } else {
        document.getElementById('chartLoyalty').parentElement.innerHTML = '<p class="text-center" style="color: var(--admin-text-muted);">No loyalty data</p>';
    }
})();
</script>
@endpush
@endsection
